### ISSUE TITLE
stream.watch should return an AsyncSnapshot?

### ISSUE THREAD

**Issue by xvrh** [s0nerik/context_watch#1]
Hello,
I had a quick look at this library, and I'm surprise the `watch` method on a stream returns `void`.
Shouldn't it returns `AsyncSnapshot` (https://api.flutter.dev/flutter/widgets/AsyncSnapshot-class.html) like the argument in the `StreamBuilder`?

**Comment by s0nerik** [comment]
Hey, Xavier. This sounds like a good idea to me. Will look into adding this soon. Thanks for pointing this out.

**Comment by s0nerik** [comment]
Implemented in [v2.0.0](https://pub.dev/packages/context_watch/versions/2.0.0-dev.3)
